package aplicacion.modelo.dominio;
// Generated 11/07/2019 12:45:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ModoPago generated by hbm2java
 */
public class ModoPago  implements java.io.Serializable {


     private int idmodoPago;
     private String descripcion;
     private Integer cuotas;
     private Double interes;
     private Set facturas = new HashSet(0);

    public ModoPago() {
    }

	
    public ModoPago(int idmodoPago) {
        this.idmodoPago = idmodoPago;
    }
    public ModoPago(int idmodoPago, String descripcion, Integer cuotas, Double interes, Set facturas) {
       this.idmodoPago = idmodoPago;
       this.descripcion = descripcion;
       this.cuotas = cuotas;
       this.interes = interes;
       this.facturas = facturas;
    }
   
    public int getIdmodoPago() {
        return this.idmodoPago;
    }
    
    public void setIdmodoPago(int idmodoPago) {
        this.idmodoPago = idmodoPago;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getCuotas() {
        return this.cuotas;
    }
    
    public void setCuotas(Integer cuotas) {
        this.cuotas = cuotas;
    }
    public Double getInteres() {
        return this.interes;
    }
    
    public void setInteres(Double interes) {
        this.interes = interes;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


